mod helloworld;
mod datatypes;
mod operators;
mod scope_and_shadowing;
mod global_variables;
mod stack_and_heap;
mod control_flow;
mod structs;
mod enums;
mod unions;
mod options;
mod arrays;
mod vectors;
mod slices;
mod strings;
mod tuples;
mod pattern_matching;
mod generics;
mod functions;
mod methods;
mod closures;
mod higher_order_functions;
mod traits;
mod operator_overloading;
mod static_dynamic_dispatch;
mod ownership_and_memory_safety;
mod borrowing;

fn main() {
    helloworld::main();
    datatypes::main();
    operators::main();
    scope_and_shadowing::main();
    global_variables::main();
    stack_and_heap::main();
    control_flow::main();
    structs::main();
    enums::main();
    unions::main();
    options::main();
    arrays::main();
    vectors::main();
    slices::main();
    strings::main();
    tuples::main();
    pattern_matching::main();
    generics::main();
    functions::main();
    methods::main();
    closures::main();
    higher_order_functions::main();
    traits::main();
    operator_overloading::main();
    static_dynamic_dispatch::main();
    ownership_and_memory_safety::main();
    borrowing::main();
}
